import axios from "axios";

let access_token = "";

let REF_PIT_SCOUTING = "30a3763d612844c285b9e93d4bf72b64_5e2e47027b041";
let REF_MATCH_SCOUTING = "30a3763d612844c285b9e93d4bf72b64_5e2e4ee002375";

// Generated by Postman (THANK YOU POSTMAN!!!)
export async function GetToken(next, err) {
  var myHeaders = new Headers();
  myHeaders.append("Content-Type", "application/json");

  var raw = JSON.stringify({
    grant_type: "client_credentials",
    client_id: 1428,
    client_secret: "iruBoItL9XjiEeQp3v9OPPXIRzqc2uSl0z0cJQOM"
  });

  var requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: raw,
    redirect: "follow"
  };

  fetch("https://five.epicollect.net/api/oauth/token", requestOptions)
    .then(response => response.json())
    .then(result => next(result))
    .catch(error => {
      err(error);
    });
}

export async function FetchAllTeams(next, err) {
  if (access_token === "") {
    GetToken(
      res => {
        console.log(res);
        access_token = "Bearer " + res.access_token;
        setTimeout(FetchAllTeams(next, err), 1000);
      },
      err => {
        console.log("error", err);
      }
    );
  } else {
    console.log("AT = " + access_token);
    try {
      const response = await axios.get(
        "https://five.epicollect.net/api/export/entries/team-5876-infinite-recharge-scouting",
        {
          headers: {
            Authorization: access_token
          }
        }
      );
      next(response);
    } catch (error) {
      err(error);
    }
  }
}

export async function FetchSingleTeam(puid, next, err) {
  if (access_token === "") {
    GetToken(
      res => {
        console.log(res);
        access_token = "Bearer " + res.access_token;
        setTimeout(FetchAllTeams(next, err), 1000);
      },
      err => {
        console.log("error", err);
      }
    );
  } else {
    console.log("AT = " + access_token);
    try {
      const response = await axios.get(
        "https://five.epicollect.net/api/export/entries/team-5876-infinite-recharge-scouting",
        {
          headers: {
            Authorization: access_token
          }
        }
      );
      next(response);
    } catch (error) {
      err(error);
    }
  }
}
